# @package _global_

#### Model params #############################################################
model:
  name: ols
  hparams:
    alpha : 0.00001
    fit_intercept: True
    copy_X : True
    tol : 0.00001
    solver : 'svd'
