# @package _global_

#### Dataset params ###########################################################
dataset:
  name: ???
  splitting:
    val_len: 0.1
    test_len: 0.2
  connectivity:
    method: distance
    threshold: 0.1
    include_self: False
    layout: edge_index
