defaults:
  - _self_
  - dataset: ettm1
  - model: dlinear
  - logger: neptune
  - lr_scheduler: cosine
  - optimizer: adam

#### Experiment params ########################################################
hydra:
  run:
    dir: logs/${model.name}/${dataset.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: logs/${now:%Y-%m-%d-%H-%M-%S}
    subdir: ${model.name}/${dataset.name}/${hydra.job.num}

seed: 114  # automatically set everywhere the seed
tags:
  - 'traffic'
  - ${model.name}
  - ${dataset.name}

workers: 0
num_threads: 1  # limit the number of pytorch threads spawn


#### Windowing params #########################################################
window: 96
horizon: 96
stride: 1

#### Training params ##########################################################
epochs: 1
patience: 10
batch_size: 64
grad_clip_val: 5
scale_target: False


