defaults:
  - default
  - override logger: neptune
  - override optimizer: adam
  - override hydra/sweeper: optuna # {optuna, basic}
  - override hydra/sweeper/sampler: grid # {tpe, random, grid}


  - _self_

default_tags:
  - ${model.name}
  - ${dataset.name}
  - tpe
  
#### Experiment params ########################################################
hydra:
  mode: MULTIRUN
  sweeper:
    direction: minimize  # minimize if loss is MSE
    n_trials: 100
    n_jobs: 1
    storage: null
    params:
      # Constant params
      window: 48
      horizon: 96
      optimizer.hparams.lr: 0.000005, 0.00001, 0.00005
      dataset: etth2
      model: fcinformer
      lr_scheduler: multistep, cosine
      # lr_scheduler.hparams.gamma: 1.0
      model.hparams.hidden_size: 128, 256, 512, 1024
      model.hparams.e_layers: 1, 2, 4
      model.hparams.d_layers: 1, 2, 4
      model.hparams.attn: prob
      model.hparams.factor: 3, 5, 8
      model.hparams.dropout: 0.05
      model.hparams.padding: 0
      model.hparams.n_heads: 8, 16, 32
      model.hparams.embed: timeF
      model.hparams.activation: gelu
      model.hparams.distil: True
      model.hparams.output_attention: False
      model.hparams.mix: True
      model.hparams.d_ff: 1024, 2048
      train_batches: 1.0
      axis: 1 #TODO put 1
      epochs: 40
      batch_size: 32
      patience: 10
      num_nodes_transform: 3 #TODO ATTENZIONE SE != 0

      
      
      

run:
  max_workers: 1
