defaults:
  - default
  - override logger: neptune
  - override optimizer: adam
  - override hydra/sweeper: optuna # {optuna, basic}
  - override hydra/sweeper/sampler: grid # {tpe, random, grid}


  - _self_

default_tags:
  - ${model.name}
  - ${dataset.name}
  - tpe
  
#### Experiment params ########################################################
hydra:
  mode: MULTIRUN
  sweeper:
    direction: minimize  # minimize if loss is MSE
    n_trials: 1
    n_jobs: 1
    storage: null
    params:
      # Constant params
      window: 48
      optimizer.hparams.lr: 0.00005
      dataset: electricity
      model: rnn
      lr_scheduler: exp
      lr_scheduler.hparams.gamma: 1.0
      model.hparams.hidden_size: 128
      model.hparams.rec_layers: 4
      # model.hparams.n_layers: 1
      # model.hparams.n_heads: 1
      model.hparams.ff_size: 32
      # model.hparams.kernel_size: 7, 15, 31
      train_batches: 1.0
      axis: 1
      bool_iid_dataset: False
      epochs: 120

      
      
      

run:
  max_workers: 1
