defaults:
  - default
  - override logger: neptune
  - override optimizer: adam
  - override hydra/sweeper: optuna # {optuna, basic}
  - override hydra/sweeper/sampler: grid # {tpe, random, grid}


  - _self_

default_tags:
  - ${model.name}
  - ${dataset.name}
  - tpe
  
#### Experiment params ########################################################
hydra:
  mode: MULTIRUN
  sweeper:
    direction: minimize  # minimize if loss is MSE
    n_trials: 100
    n_jobs: 1
    storage: null
    params:
      # Constant params
      window: 32
      optimizer.hparams.lr: 0.0005
      dataset: electricity
      model: rnn
      lr_scheduler: exp
      lr_scheduler.hparams.gamma: 0.99
      model.hparams.hidden_size: 16
      model.hparams.rec_layers: 1, 2, 4
      # model.hparams.n_layers: 1
      # model.hparams.n_heads: 1
      # model.hparams.ff_size: 16
      # model.hparams.kernel_size: 7, 15, 31

      
      

run:
  max_workers: 1
