# @package _global_

#### Model params #############################################################
model:
  name: multivrnn
  hparams:
    hidden_size: 128
    ff_size: 64
    rec_layers: 2
    ff_layers: 1
    rec_dropout: 0.1
    ff_dropout: 0.1
    cell_type: gru
