# @package _global_

#### Model params #############################################################
model:
  name: rlinear
  hparams: 
    bool_individual: False
    bool_rev: True
    bool_drop: True
